on: 
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v3
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Setup Terraform & Terragrunt
        run: |
          brew install tfenv warrensbox/tap/tgswitch cowsay
          tfenv install
          tgswitch -c $GITHUB_WORKSPACE
      - name: cache build
        id: cache-build
        uses: actions/cache@v3
        with:
          key: ${{ github.sha }}-terragrunt-cache
          path: |
            **/.terragrunt-cache/**
            **/.terraform.lock.hcl
      - name: cache plan
        id: cache-plan
        uses: actions/cache@v3
        with:
          key: ${{ github.sha }}-terragrunt-plan
          path: |
            **/tgplan.out
      #  TODO: parametrize
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::943824751361:role/github-ci
          aws-region: eu-west-1
      - name: terragrunt apply
        id: apply
        run: terragrunt apply
