on: 
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      ci-role-name:
        type: string
        required: false
        description: 'Name of the IAM role to assume'
        default: 'github-ci'
      target-account-id:
        required: true
        type: string
        description: 'A Target AWS Account ID'
      target-region:
        type: string
        required: false
        description: 'A Target AWS Region'

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v3
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Setup Terraform & Terragrunt
        run: |
          brew install tfenv warrensbox/tap/tgswitch cowsay
          tfenv install
          tgswitch
      - name: cache build
        id: cache-build
        uses: actions/cache@v3
        with:
          key: ${{ github.sha }}-terragrunt-cache
          path: |
            **/.terragrunt-cache/**
            **/.terraform.lock.hcl
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ inputs.target-account-id }}:role/${{ inputs.ci-role-name }}
          aws-region: ${{ inputs.target-region }}
      - name: terragrunt plan
        id: plan
        run: terragrunt plan
        working-directory: ${{ inputs.working-directory }}
      - name: cache plan
        id: cache-plan
        uses: actions/cache@v3
        with:
          key: ${{ github.sha }}-terragrunt-plan
          path: |
            **/tgplan.out
